
13/10/2023 10:10:56: System.Net.Http.HttpRequestException: Ocorreu um erro ao enviar a solicitação. ---> System.Net.WebException: O nome remoto não pôde ser resolvido: 'raw.githubusercontent.com'
   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__23.MoveNext()
13/10/2023 10:10:56: System.Net.WebException: O nome remoto não pôde ser resolvido: 'raw.githubusercontent.com'
   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
05/11/2023 10:30:52: System.Net.Http.HttpRequestException: Ocorreu um erro ao enviar a solicitação. ---> System.Net.WebException: O nome remoto não pôde ser resolvido: 'raw.githubusercontent.com'
   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__24.MoveNext()
05/11/2023 10:30:52: System.Net.WebException: O nome remoto não pôde ser resolvido: 'raw.githubusercontent.com'
   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
08/01/2024 21:54:05: System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em FanControl.App.OnExit(ExitEventArgs e)